### PR TITLE
Add support for GHC >= 8 and dropped support for older versions

### LINKED ISSUE #32: Provide an explanation about how cyclomatic complexity is measured
Hi,

It'd be nice to have an explanation about what the different figures (1, 5, 10) actually mean. Cyclomatic complexity is usually defined for imperative programs, but I could not find what is the definition of cyclomatic complexity that `argon` uses. If you have a reference to a paper or article I can help with updating the readme.

### PR DESCRIPTION
**Pull request by capitanbatata**
This PR contain the following proposals:

- Drop support for GHC < 8
- Add support for GHC >= 8
- Drop support for test coverage at the travis script (stack-hpc-coverals) not available for GHC 8.2.2.
- Update the readme:
  + Explanation of cyclomatic complexity
  + Mention which versions of GHC are now supported
- Remove the dependency on `pipes-files`, which is not maintained anymore. This also enables the build of `argon` on Windows.

Fixes #32

### CODE REVIEW

**Comment by rubik** [comment]
Wow you did an amazing job! I'm really grateful because in the last few months I have been too busy to maintain it. If you agree I would add you as a collaborator on the project so you can become the maintainer.

**Comment by capitanbatata** [comment]
On the contrary, thanks for all the work you put into developing this tool!

Feel free to add me as a collaborator, I'll try to keep `argon` up to date for future versions of GHC, and maybe add some more functionality. I'll always include you in the pull requests so that you can give me your blessing :)

BTW, could you add me as a collaborator on hackage as well, so I can upload the new version.

**Comment by rubik** [comment]
Sure, done. I actually wasn't aware of this possibility.

**Comment by nh2** [comment]
@dnadales Do you still intend to upload the change here to Hackage? It still has the old version.

See also:

* https://github.com/JohnLato/posix-paths/issues/26

**Comment by rubik** [comment]
@nh2 Thanks for the heads up, I uploaded the current version as 0.4.2.0 to Hackage. It's tested on GHC 8.2.2.

**Pull request merged**
